#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Sun Jul 29 14:12:54 2007

import wx

tree1 = [
        "Event 1",
        ["Event 2", [
            "Spike 1",
            "Spike 2",
            "Spike 3",
            ]],
        "Event 3",
        ]

tree2 = [
        "Spike 235",
        "Spike 73",
        "Spike 23",
        ]

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.tree_ctrl_2 = wx.TreeCtrl(self, -1, style=wx.TR_HAS_BUTTONS|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.tree_ctrl_3 = wx.TreeCtrl(self, -1, style=wx.TR_HAS_BUTTONS|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)

        root1 = self.tree_ctrl_2.AddRoot("Events")
        root2 = self.tree_ctrl_3.AddRoot("Spikes")

        self.AddTreeNodes(self.tree_ctrl_2, root1, tree1)
        self.AddTreeNodes(self.tree_ctrl_3, root2, tree2)

        self.tree_ctrl_2.Expand(root1)
        self.tree_ctrl_3.Expand(root2)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def AddTreeNodes(self, tree, parentItem, items):
        """
        Recursively traverses the data structure, adding tree nodes to
        match it.
        """
        for item in items:
            if type(item) == str:
                tree.AppendItem(parentItem, item)
            else:
                newItem = tree.AppendItem(parentItem, item[0])
                self.AddTreeNodes(tree, newItem, item[1])

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(self.tree_ctrl_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.tree_ctrl_3, 1, wx.EXPAND, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()

